AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.8
  Hubitat home automation integrations.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  DoorNotificationHandler:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        EmailNotificationSource:
          Type: SNS
          Properties:
            # FilterPolicy: SnsFilterPolicy
            Region: us-east-1
            SqsSubscription: false
            Topic: arn:aws:sns:us-east-1:297473205123:adt-email-notifications
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./integrations
      DockerTag: python3.8-v1

  DeviceCacherFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        RefreshSchedule:
          Type: Schedule
          Properties:
            DeadLetterConfig:
              Type: SQS
              QueueLogicalId: DeviceCacherFailures
            Description: DeviceCacher refresh schedule.
            Enabled: true
            Name: device-cacher-schedule
            RetryPolicy:
              MaximumEventAgeInSeconds: 60
              MaximumRetryAttempts: 0
            Schedule: rate(5 minutes)
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./device_cacher
      DockerTag: python3.8-v1

  DeviceCacheBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: com.everythingbiig.hubitat
      PolicyDocument:
        Statement:
          - Action:
              - 's3:PutObject'
              - 's3:GetObject'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - com.everythingbiig.hubitat
                - /*
            Principal:
              AWS:
                - !GetAtt DeviceCacherFunctionRole.Arn
                - !GetAtt DoorNotificationHandlerRole.Arn

Outputs:
  DoorNotificationHandler:
    Description: "DoorNotificationHandler Function ARN"
    Value: !GetAtt DoorNotificationHandler.Arn
  DeviceCacherFunction:
    Description: "DeviceCacherFunction Function ARN"
    Value: !GetAtt DeviceCacherFunction.Arn
  DoorNotificationHandlerIamRole:
    Description: "Implicit IAM Role created for RefreshDeviceCacheEventHandler function"
    Value: !GetAtt DoorNotificationHandlerRole.Arn
  DeviceCacherFunctionIamRole:
    Description: "Implicit IAM Role created for DeviceCacherFunction function"
    Value: !GetAtt DeviceCacherFunctionRole.Arn
